import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen flex flex-col bg-slate-50">
      <header className="border-b bg-white">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="text-sm font-semibold tracking-tight">M&amp;A Platform</Link>
          <Link href="/" className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md border bg-background text-sm font-medium hover:bg-muted">
            <ArrowLeft className="h-3.5 w-3.5" />
            Back to site
          </Link>
        </div>
      </header>

      <main className="flex-1 max-w-3xl mx-auto w-full px-6 py-12 space-y-8">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight mb-2">Legal disclaimer &amp; ownership</h1>
          <p className="text-sm text-muted-foreground">Last updated {new Date().toLocaleDateString()}</p>
        </div>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold tracking-tight">Ownership</h2>
          <p className="text-sm leading-relaxed text-slate-700">
            This application, including all of its source code, design, structure, logic, data models, user interface, and all related intellectual property, is the exclusive property of Rocky W. Hill of Frisco, Texas.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold tracking-tight flex items-center gap-2">
            <span className="text-warning">⚠</span> Prohibited Use
          </h2>
          <p className="text-sm leading-relaxed text-slate-700">
            The copying, reproduction, distribution, modification, reverse engineering, or use, in whole or in part, of any of the following elements is strictly prohibited without the explicit written consent of Rocky W. Hill:
          </p>
          <ul className="list-disc pl-6 text-sm space-y-2 text-slate-700">
            <li>Source code, including server, client, and infrastructure logic</li>
            <li>Visual design, layout, color schemes, typography, and component patterns</li>
            <li>Data models, database schemas, and parsing logic</li>
            <li>User interface flows, navigation patterns, and interaction designs</li>
            <li>Report templates, signal detection algorithms, and analytical methodologies</li>
            <li>Branding elements, including logos, names, and trade dress</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold tracking-tight">Written Consent Requirement</h2>
          <p className="text-sm leading-relaxed text-slate-700">
            Any request to use, reference, adapt, or incorporate any portion of this application must be submitted in writing to Rocky W. Hill of Frisco, Texas, and must receive explicit written approval prior to any use. Verbal agreements or implied permissions are not valid. Unauthorized use may subject the infringing party to legal action under applicable copyright and intellectual property laws.
          </p>
        </section>

        <section className="space-y-4 pt-4 border-t">
          <h2 className="text-xl font-semibold tracking-tight">No financial advice</h2>
          <p className="text-sm leading-relaxed text-slate-700">
            The analyses, signals, valuations, and reports generated by this platform are computational outputs based on user-supplied data. They do not constitute financial, legal, accounting, or tax advice. Users are solely responsible for verifying all numbers, conclusions, and recommendations against original source documents and qualified professional advisors before making any investment, transaction, or business decision.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold tracking-tight">No warranty</h2>
          <p className="text-sm leading-relaxed text-slate-700">
            This software is provided &quot;as is&quot; without warranty of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, accuracy, or non-infringement. The platform owner shall not be liable for any damages arising from the use or inability to use the software.
          </p>
        </section>

        <div className="pt-8 border-t">
          <Link href="/" className="inline-flex items-center gap-1.5 px-4 py-2 rounded-md bg-primary text-primary-foreground text-sm font-medium hover:opacity-90">
            <ArrowLeft className="h-3.5 w-3.5" />
            Back to site
          </Link>
        </div>
      </main>

      <footer className="border-t bg-white py-4 px-6">
        <p className="text-xs text-slate-500 text-center">© {new Date().getFullYear()} NeuralEdge. All rights reserved.</p>
      </footer>
    </div>
  );
}
